# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=32)),
                ('elevation', models.IntegerField()),
                ('metar', models.CharField(blank=True, max_length=512, null=True)),
                ('taf', models.CharField(blank=True, max_length=1024, null=True)),
                ('sunrise', models.CharField(blank=True, max_length=64, null=True)),
                ('sunset', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.IntegerField(choices=[(1, 'Common Traffic Advisory Frequency'), (2, 'Universal Communications'), (3, 'Weather'), (4, 'Ground'), (5, 'Tower'), (6, 'Approach'), (7, 'Departure'), (8, 'Clearance')], default=1)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surface_type', models.IntegerField(choices=[(1, 'Asphalt'), (2, 'Concrete'), (3, 'Grass')], default=1)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bearing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.Airport')),
            ],
        ),
    ]
