# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='elevation',
            field=models.IntegerField(help_text='MSL, feet'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='icao',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='sunrise',
            field=models.DateTimeField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='sunset',
            field=models.DateTimeField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='bearing',
            field=models.DecimalField(decimal_places=2, help_text='Bearing in degrees', max_digits=5),
        ),
        migrations.AlterField(
            model_name='runway',
            name='length',
            field=models.DecimalField(decimal_places=2, help_text='Length in feet', max_digits=7),
        ),
        migrations.AlterField(
            model_name='runway',
            name='surface_type',
            field=models.IntegerField(choices=[(1, 'Asphalt'), (2, 'Concrete'), (3, 'Grass'), (4, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='runway',
            name='width',
            field=models.DecimalField(decimal_places=2, help_text='Width in feet', max_digits=7),
        ),
    ]
