# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_auto_20180704_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportcomm',
            name='frequency',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
