# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0004_auto_20180707_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='last_weather',
            field=models.DateTimeField(blank=True, max_length=64, null=True),
        ),
    ]
