# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0005_airport_last_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='region',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
